WebAPICase/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using WebAPICase.Areas.HelpPage.ModelDescriptions;
using WebAPICase.Areas.HelpPage.Models;

namespace WebAPICase.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

WebAPICase/Controllers/HistoricoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using WebAPICase.Data;
using WebAPICase.Models;

namespace WebAPICase.Controllers
{
    public class HistoricoController : ApiController
    {
        DataContext dataContext = new DataContext();

        // GET: api/Historico
        public IEnumerable<Historico> Get()
        {
            return dataContext.Historico.AsQueryable();
        }

        // GET: api/Historico/5
        public Historico Get(int id)
        {
            return dataContext.Historico.Find(id);
        }

        // POST: api/Historico
        [HttpPost]
        public void Post([FromBody]Historico historico)
        {
            dataContext.Historico.Add(historico);
            dataContext.SaveChanges();
        }

        // PUT: api/Historico/5
        [HttpPut]
        public void Put(int id, [FromBody]Historico historico)
        {
            dataContext.Entry(historico).State = System.Data.Entity.EntityState.Modified;
            dataContext.SaveChanges();
        }

        // DELETE: api/Historico/5
        [HttpDelete]
        public void Delete(int id)
        {
            var historico = dataContext.Historico.Find(id);
            dataContext.Historico.Remove(historico);
            dataContext.SaveChanges();
        }

        [HttpGet]
        public IEnumerable<string[]> MediaCombustivelVendaPorMunicipio()
        {
            List<string[]> result = new List<string[]>();

            var listMunicipio = dataContext.Historico.ToList().OrderBy(h => h.municipio).Select(m => m.municipio).Distinct();

            foreach (var municipio in listMunicipio)
            {
                //Primeiro campor é o nome do municipio e o segundo é o valor de venda
                result.Add(new string[] { municipio, "R$ " + dataContext.Historico.Where(h => h.municipio == municipio).Average(m => m.valorVenda).ToString() });
            }

            return result;
        }

        [HttpGet]
        public IEnumerable<IEnumerable<Historico>> HistoricoPorRegiao()
        {
            var listHistorico = dataContext.Historico.GroupBy(h => h.regiao).Select(grp => grp.ToList()).ToList();

            return listHistorico;
        }

        [HttpGet]
        public IEnumerable<IEnumerable<Historico>> HistoricoPorDistribuidora()
        {
            var listHistorico = dataContext.Historico.GroupBy(h => h.revenda).Select(grp => grp.ToList()).ToList();

            return listHistorico;
        }

        [HttpGet]
        public IEnumerable<IEnumerable<Historico>> HistoricoPorDataColeta()
        {
            var listHistorico = dataContext.Historico.GroupBy(h => h.dataColeta).Select(grp => grp.ToList()).ToList();

            return listHistorico;
        }

        [HttpGet]
        public IEnumerable<string[]> MediaCombustivelCompravendaPorMunicipio()
        {
            List<string[]> result = new List<string[]>();

            var listMunicipio = dataContext.Historico.ToList().OrderBy(h => h.municipio).Select(m => m.municipio).Distinct();

            foreach (var municipio in listMunicipio)
            {
                //Primeiro campor é o nome do municipio, o segundo é o valor de compra e o terceiro é o valor de venda
                result.Add(new string[] { municipio, "R$ " + dataContext.Historico.Where(h => h.municipio == municipio).Average(m => m.valorCompra).ToString(), "R$ " + dataContext.Historico.Where(h => h.municipio == municipio).Average(m => m.valorVenda).ToString() });
            }

            return result;
        }

        [HttpGet]
        public IEnumerable<string[]> MediaCombustivelCompravendaPorBandeira()
        {
            List<string[]> result = new List<string[]>();

            var listBandeira = dataContext.Historico.ToList().OrderBy(h => h.bandeira).Select(m => m.bandeira).Distinct();

            foreach (var bandeira in listBandeira)
            {
                //Primeiro campor é o nome da bandeira, o segundo é o valor de compra e o terceiro é o valor de venda
                result.Add(new string[] { bandeira, "R$ " + dataContext.Historico.Where(h => h.bandeira == bandeira).Average(m => m.valorCompra).ToString(), "R$ " + dataContext.Historico.Where(h => h.bandeira == bandeira).Average(m => m.valorVenda).ToString() });
            }

            return result;
        }
    }
}

WebAPICase/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using WebAPICase.Data;
using WebAPICase.Models;

namespace WebAPICase.Controllers
{
    public class UsuarioController : ApiController
    {
        DataContext dataContext = new DataContext();

        Usuario usuario = new Usuario();

        // GET: api/Usuario
        [HttpGet]
        public IEnumerable<Usuario> Get()
        {
            var listUsuario = dataContext.Usuario.AsQueryable();

            return listUsuario;
        }

        // GET: api/Usuario/5
        [HttpGet]
        public Usuario Get(int id)
        {
            return dataContext.Usuario.Where(u => u.idUsuario == id).FirstOrDefault();
        }

        // POST: api/Usuario
        [HttpPost]
        public void Post([FromBody]Usuario usuario)
        {
            dataContext.Usuario.Add(usuario);
            dataContext.SaveChanges();
        }

        // PUT: api/Usuario/5
        [HttpPut]
        public void Put(int id, [FromBody]Usuario usuario)
        {
            dataContext.Entry(usuario).State = System.Data.Entity.EntityState.Modified;
            dataContext.SaveChanges();
        }

        // DELETE: api/Usuario/5
        [HttpDelete]
        public void Delete(int id)
        {
            var usuario = dataContext.Usuario.Where(u => u.idUsuario == id).FirstOrDefault();
            dataContext.Usuario.Remove(usuario);
            dataContext.SaveChanges();
        }
    }
}

WebAPICase/Views/Shared/_Layout.cshtml
    <!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @if (Session["NomeUsuario"] != null)
                    {
                        <li>@Html.ActionLink("Usuarios", "Usuario", "Home", null, null)</li>
                        
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Historico <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Listar", "Historico", "Home", null, null)</li>
                                <li><a href="#" data-toggle="modal" data-target="#modalImportarHistorico">Importar</a></li>
                            </ul>
                        </li>
                    }

                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>

                @if (Session["NomeUsuario"] != null)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Sair", "Logout", "Home", null, null)</li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        @using (Html.BeginForm("Login", "Home", FormMethod.Post, new { @class = "form-inline", @style = "margin-top: 10px;" }))
                        {
                            @Html.TextBox("usuario", "", new { @class = "form-control", @placeholder = "Usuario" })
                            @Html.TextBox("senha", "", new { @type = "password", @class = "form-control", @placeholder = "Senha" })
                            <button class="btn btn-primary form-control">Entrar</button>
                        }
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    @* Itens da Notificação *@
    <input type="hidden" id="success" value="@TempData["success"]" />
    <input type="hidden" id="info" value="@TempData["info"]" />
    <input type="hidden" id="warning" value="@TempData["warning"]" />
    <input type="hidden" id="error" value="@TempData["error"]" />

    <script type="text/javascript" lang="pt-br">
        $(document).ready( function () {
            $('#dataTable').DataTable();
        });

        $(function () {
            var displayMessage = function (message, msgType) {

                toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "newestOnTop": false,
                    "progressBar": true,
                    "positionClass": "toast-top-right",
                    "preventDuplicates": false,
                    "onclick": null,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                };

                toastr[msgType](message);
            };

            if ($('#success').val()) { displayMessage($('#success').val(), 'success'); }
            if ($('#info').val()) { displayMessage($('#info').val(), 'info'); }
            if ($('#warning').val()) { displayMessage($('#warning').val(), 'warning'); }
            if ($('#error').val()) { displayMessage($('#error').val(), 'error'); }
        });
    </script>
</body>
</html>

@* MODAL IMPORTAR HISTORICO *@
<div class="modal fade" id="modalImportarHistorico" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><span class="glyphicon glyphicon-import" aria-hidden="true"></span> Importar Historico</h4>
            </div>
            @using (Html.BeginForm("ImportarHistorico", "Home", FormMethod.Post, new { @enctype = "multipart/form-data" }))
            {
                <div class="modal-body">
                    <input type="file" name="Arquivo" accept="application/csv" id="Arquivos" data-ng-model="arquivo" file-model="arquivo">
                </div>

                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Importar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            }

        </div>
    </div>
</div>